project:
  type: website

website:
  title: "Intro to Python 2"
  page-navigation: true

  sidebar: 
    title: "Intro to Python 2"
    logo: "assets/UoB_RGB_24.png"
    align: center
    logo-alt: "University of Bristol logo"
    style: "docked"
    border: true
    contents: 
      - "index.qmd"
      - "pages/001-workspace-setup.qmd"
      - section: "pages/010-advanced-data-types.qmd"
        contents:
          - "pages/012-dictionaries.qmd"
          - "pages/011-string-formatting.qmd"
          - "pages/013-list-comprehensions.qmd"
      - section: "pages/020-functions.qmd"
        contents:
          - "pages/021-importing-functions.qmd"
          - "pages/022-writing-functions.qmd"
      - "pages/030-modules.qmd"
      - "pages/040-errors-exceptions.qmd"
      - "pages/070-worksheet.qmd"
      - "pages/980-summary.qmd"
      - "pages/990-contributors.qmd"


  page-footer:
    left: "[Jean Golding Institute](https://www.bristol.ac.uk/golding/) © [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"  
  repo-url: https://github.com/bristol-training/intro-python-2
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    shift-heading-level-by: 1
    highlight-style: github

    # code-line-numbers: true

execute:
  freeze: auto
  error: true

