[workspace]
authors = ["l-gorman <leo.gorman@bristol.ac.uk>"]
channels = ["conda-forge"]
name = "intro-python-2"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
build = "quarto render"
preview = "quarto preview"

[dependencies]
quarto = ">=1.7.33,<2"
jupyterlab = ">=4.4.7,<5"
pandas = ">=2.3.2,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.6,<4"